<?php
// $Id$
/*
 *@file 
 * This module privide the accordion widget for the blocks on left and right side
 */

/*
 * Implementation of hook_init()
 */
function accordion_blocks_init() {
  // including accordion related javascript and css files
  drupal_add_library('system', 'ui.accordion');
  drupal_add_js(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.js');
  drupal_add_css(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.css');
}

/*
 * Implementation of hook_theme_registry_alter()
 */
function accordion_blocks_theme_registry_alter(&$theme_registry) {
  // using our own block.tpl.php file.
  global $theme;
  // Populate all block regions.
  $regions = system_region_list($theme);
  if(empty($regions['sidebar_first']) && empty($regions['sidebar_second']))
     return;
  $theme_registry['block']['template'] = 'block';
  $theme_registry['block']['path'] = drupal_get_path('module', 'accordion_blocks');
  $theme_registry['block']['type'] = 'module';
  $theme_registry['block']['theme path'] = drupal_get_path('module', 'accordian_blocks');
  $theme_registry['block']['theme paths'] = Array();
}

/**
 * Implementation of template_preprocess_page()
 */
function accordion_blocks_preprocess_page(&$variables){
  // to add the accordian effect add this parent div for the blocks
  if (!empty($variables['page']['sidebar_first'])) {
    $variables['page']['sidebar_first']['#theme_wrappers'][] = 'accordion_blocks';
  }

  if (!empty($variables['page']['sidebar_second'])) {
    $variables['page']['sidebar_second']['#theme_wrappers'][] = 'accordion_blocks';
  }
}

/**
 * Implementation of hook_theme()
 */
function accordion_blocks_theme() {
  return array(
    'accordion_blocks' => array(
      'render element' => 'elements', 
      'arguments' => array('elements'=>array())
    ),
  );
}

/**
 * accordion_blocks theme
 */
function theme_accordion_blocks($variables) {
  $output = '<div class="accordion_blocks_container">';
  foreach($variables['elements'] as $key => $value) {
    if (is_array($value) && array_key_exists('#children', $value)) {
      $output .= $value['#children'];
    }
  }
  $output .= '</div>';
  return $output;
}