<?php
/*
 *@file 
 * This module privide the accordion widget for the blocks on left and right side
 */

/*
 * Implements hook_init()
 */
function accordion_blocks_init() {
  // including accordion related javascript and css files
  drupal_add_library('system', 'ui.accordion');
  drupal_add_js(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.js');
  drupal_add_css(drupal_get_path('module', 'accordion_blocks') .'/accordion_init.css');
}

function accordion_blocks_preprocess_region(&$variables) {
  $regions_list = variable_get('accordion_regions',array('sidebar_first', 'sidebar_second'));  
  if ($regions_list[$variables['region']] === $variables['region']) {
    $variables['classes_array'][] = 'accordion_blocks_container';
  }
}


/**
 * Implements hook_menu()
 */ 
function accordion_blocks_menu() {
  //settings page
  $items['admin/config/user-interface/accordion-blocks'] = array(
    "title" => t("Accordion Blocks"),
    "description" => t("Configure the Regions to apply Accordion effect."),
    "page callback" => "drupal_get_form",
    "page arguments" => array('accordion_blocks_settings_form'),
    "access arguments" => array('administer site configuration'),
	);
  return $items;
}

/**
 * callback for the url admin/settings/accordion_blocks
 */
function accordion_blocks_settings_form() {
  $form = array();
  global $user;
  $themes = list_themes();
  $theme = !empty($user->theme) && !empty($themes[$user->theme]->status) ? $user->theme : variable_get('theme_default', 'garland');
  $regions_list = system_region_list($theme);
  $form['accordion_regions'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Select Regions to apply Accordion effect'),
    '#options' => $regions_list,
    '#default_value' => variable_get('accordion_regions',array('sidebar_first', 'sidebar_second')),
	);
  return system_settings_form($form);
}